import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '@/components/layout'
import styles from '@/styles/Main.module.scss'
import utility from '../styles/Utility.module.scss'
// import { db } from "../../firebase/firebase_init";
import { Container } from "@chakra-ui/react"
import { Box, Text } from "@chakra-ui/react"
import dynamic from 'next/dynamic'
const ScrollRevealContainer = dynamic(
  import('../lib/ScrollRevealContainer'),
  {ssr: false,}
);


const Home = () => {
  return (
    <Layout home>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>YoYos</title>
      </Head>
      <div className={styles.container}>
          <Box minH="340px" bg="aliceblue" color="black">
            <Text as="h2">section 1</Text>
          </Box>
          <ScrollRevealContainer>
            <Box minH="340px" bg="lavender" color="black">
              section 2
            </Box>
          </ScrollRevealContainer>
          <ScrollRevealContainer>
            <Box minH="340px" bg="lightyellow" color="black">
              section 3
            </Box>
          </ScrollRevealContainer>
          <ScrollRevealContainer>
            <Box minH="340px" bg="gainsboro" color="black">
              section 4
            </Box>
          </ScrollRevealContainer>
      </div>
    </Layout>
  )
}
export default Home;



// export function getStaticProps(){
//   const ref = db.collection("users");
//   const users_snapshot = ref.get();
//   let getUser = JSON.parse('[]');
//   users_snapshot.then((users) =>
//     users.forEach((user) => {
//       console.log(
//         `id: ${user.id}, name: ${user.data().name}, age: ${user.data().age}`
//       );
//       let views = JSON.parse(`{"id":"${user.id}", "name": "${user.data().name}", "age": ${user.data().age}}`);
//       console.log(views);
//       getUser.push(views);
//       console.log(getUser);
//     })
//   );
// 	return {
// 		props: {
//       getUser
//     }
// 	}
// }