import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/layout'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Main.module.scss'
import utility from '../styles/Utility.module.scss'
 
const Home: NextPage = () => {
  return (
    <Layout home>
      <Head>
        <title>YoYo's</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link
         href={`about`}>
          <a className={`${utility.button}  ${utility.m8}`}>About</a>
        </Link>
      </main>
      <footer>f</footer>
    </Layout>
  )
}

export default Home