import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/layout'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Main.module.scss'
import utility from '../styles/Utility.module.scss'
// import { db } from "../../firebase/firebase_init";
import { Container } from "@chakra-ui/react"
import { Box } from "@chakra-ui/react"
import Dynamic from 'next/dynamic'
const ScrollRevealContainer = Dynamic(
  import('../lib/ScrollRevealContainer'),
  {ssr: false,}
);

export default function Home() {
  return (
    <Layout home>
      <Head>
        <title>YoYos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`main`}>
        <Container>
          <Box minH="340px">
            section 1
          </Box>
          <ScrollRevealContainer>
            <Box minH="340px" bg="tomato" color="white">
              section 2
            </Box>
          </ScrollRevealContainer>
          <ScrollRevealContainer>
            <Box minH="340px">
              section 3
            </Box>
          </ScrollRevealContainer>
          <ScrollRevealContainer>
            <Box minH="340px">
              section 4
            </Box>
          </ScrollRevealContainer>
        </Container>
      </div>
      <Link
       href={`/about`}>
        <a className={`${utility.button}  ${utility.m8}`}>About</a>
      </Link>
      <style jsx>{`
        .main {
          min-height: 150vh;
        } 
      `}</style>
    </Layout>
  )
}



// export function getStaticProps(){
//   const ref = db.collection("users");
//   const users_snapshot = ref.get();
//   let getUser = JSON.parse('[]');
//   users_snapshot.then((users) =>
//     users.forEach((user) => {
//       console.log(
//         `id: ${user.id}, name: ${user.data().name}, age: ${user.data().age}`
//       );
//       let views = JSON.parse(`{"id":"${user.id}", "name": "${user.data().name}", "age": ${user.data().age}}`);
//       console.log(views);
//       getUser.push(views);
//       console.log(getUser);
//     })
//   );
// 	return {
// 		props: {
//       getUser
//     }
// 	}
// }